variables: 
    GRADLE_OPTS: "-Dorg.gradle.daemon=false" 
    IMAGE_NAME: "your-dockerhub-username/spring-boot-app"
    CONTAINER_NAME: "spring-boot-app"
    DOCKER_HOST: tcp://docker:2375/

services:
  - docker:dind 

image: docker:latest

# before_script:
#   - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

stages:   
    - build 
    - sonar

build: 
    stage: build 
    script: 
        - ./gradlew assemble
        - docker build -t caresync-be-app:latest .
        - docker push caresync-be-app:latest

sonar:
    stage: sonar
    script: ./gradlew sonar



 



