variables: 
    GRADLE_OPTS: "-Dorg.gradle.daemon=false" 
    IMAGE_NAME: caresync-be-app
    AZURE_REGISTRY: backendsem6.azurecr.io  # Replace with your Azure Container Registry URL
    RESOURCE_GROUP: individual      # Replace with your Azure resource group
    APP_SERVICE_NAME: caresync-be  # Replace with your App Service name

services:
  - docker:dind 

stages:   
    - build 
    - build-images
    - sonar
    - push
    - deploy


before_script:
  - if [ "$CI_COMMIT_BRANCH" != "main" ]; then exit 0; fi
  - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
  - az acr login --name $AZURE_REGISTRY


build: 
    stage: build 
    script: 
        - ./gradlew assemble

build-images:
  stage: build-images
  script:
    - docker build -t ${AZURE_REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_SHA} .
    - docker tag ${AZURE_REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_SHA} ${AZURE_REGISTRY}/${IMAGE_NAME}:latest
  only:
    - main


sonar:
  stage: sonar
  script: 
     - ./gradlew build
     - ./gradlew sonar
  only:
    - main
    

push:
  stage: push
  script:
    - docker push ${AZURE_REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_SHA}
    - docker push ${AZURE_REGISTRY}/${IMAGE_NAME}:latest
  only:
    - main
    

deploy:
  stage: deploy
  script:
    - echo "Deploying to Azure App Service..."
    - az webapp config container set --name ${APP_SERVICE_NAME} --resource-group ${RESOURCE_GROUP} --docker-custom-image-name ${AZURE_REGISTRY}/${IMAGE_NAME}:latest --docker-registry-server-url https://${AZURE_REGISTRY}
    - az webapp restart --name ${APP_SERVICE_NAME} --resource-group ${RESOURCE_GROUP}
  only:
    - main