variables: 
    GRADLE_OPTS: "-Dorg.gradle.daemon=false" 

services:
  - docker:dind 

# before_script:
#   - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

stages:   
    - build 
    - sonar
    - deploy

build: 
    stage: build 
    script: 
        - ./gradlew assemble

sonar:
    stage: sonar
    script: 
     - ./gradlew sonar
     - if ($CI_COMMIT_REF_NAME -eq "main") { ./gradlew sonar } else { echo "Skipping SonarQube analysis for non-main branch." }


deploy:
    stage: deploy
    only:
        - main
    script:
        - docker-compose -f docker-compose.yml down
        - docker-compose -f docker-compose.yml up -d



 



